"""inventory foundation

Revision ID: 2990ee6aa213
Revises: 0a79316d69b0
Create Date: 2026-07-22 08:58:11.309818

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2990ee6aa213"
down_revision: str | Sequence[str] | None = "0a79316d69b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_levels",
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("product_variant_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("client_uuid", sa.UUID(), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_stock_levels_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_levels_product_variant_id_product_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_levels_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_levels")),
        sa.UniqueConstraint(
            "company_id",
            "warehouse_id",
            "product_variant_id",
            name="uq_stock_levels_company_warehouse_variant",
        ),
    )
    op.create_index(
        op.f("ix_stock_levels_company_id"), "stock_levels", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_levels_product_variant_id"),
        "stock_levels",
        ["product_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_levels_warehouse_id"), "stock_levels", ["warehouse_id"], unique=False
    )
    op.create_table(
        "stock_transfers",
        sa.Column("from_warehouse_id", sa.UUID(), nullable=False),
        sa.Column("to_warehouse_id", sa.UUID(), nullable=False),
        sa.Column("product_variant_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_stock_transfers_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["from_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transfers_from_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_transfers_product_variant_id_product_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["to_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transfers_to_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
    )
    op.create_index(
        op.f("ix_stock_transfers_company_id"), "stock_transfers", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_from_warehouse_id"),
        "stock_transfers",
        ["from_warehouse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_product_variant_id"),
        "stock_transfers",
        ["product_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_to_warehouse_id"),
        "stock_transfers",
        ["to_warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_transactions",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("product_variant_id", sa.UUID(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "stock_in",
                "stock_out",
                "transfer_out",
                "transfer_in",
                "adjustment",
                name="movementtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("quantity_after", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("transfer_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["branches.id"], name=op.f("fk_stock_transactions_branch_id_branches")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_stock_transactions_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_stock_transactions_product_variant_id_product_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["stock_transfers.id"],
            name=op.f("fk_stock_transactions_transfer_id_stock_transfers"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_transactions_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transactions")),
    )
    op.create_index(
        op.f("ix_stock_transactions_branch_id"), "stock_transactions", ["branch_id"], unique=False
    )
    op.create_index(
        "ix_stock_transactions_company_created_at",
        "stock_transactions",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_company_id"), "stock_transactions", ["company_id"], unique=False
    )
    op.create_index(
        "ix_stock_transactions_company_variant_created_at",
        "stock_transactions",
        ["company_id", "product_variant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_product_variant_id"),
        "stock_transactions",
        ["product_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_transfer_id"),
        "stock_transactions",
        ["transfer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_warehouse_id"),
        "stock_transactions",
        ["warehouse_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_transactions_warehouse_id"), table_name="stock_transactions")
    op.drop_index(op.f("ix_stock_transactions_transfer_id"), table_name="stock_transactions")
    op.drop_index(op.f("ix_stock_transactions_product_variant_id"), table_name="stock_transactions")
    op.drop_index(
        "ix_stock_transactions_company_variant_created_at", table_name="stock_transactions"
    )
    op.drop_index(op.f("ix_stock_transactions_company_id"), table_name="stock_transactions")
    op.drop_index("ix_stock_transactions_company_created_at", table_name="stock_transactions")
    op.drop_index(op.f("ix_stock_transactions_branch_id"), table_name="stock_transactions")
    op.drop_table("stock_transactions")
    op.drop_index(op.f("ix_stock_transfers_to_warehouse_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_product_variant_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_from_warehouse_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_company_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index(op.f("ix_stock_levels_warehouse_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_product_variant_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_company_id"), table_name="stock_levels")
    op.drop_table("stock_levels")
    # ### end Alembic commands ###
