"""Declarative base and cross-cutting column mixins.

Implements the standard column set every tenant-scoped table gets, per
SPRINT0.md §5.1. No concrete tables are declared here — the first real
tables (companies, branches, users, ...) land with the Identity module in
Sprint 2, at which point they inherit `Base` and the mixins below.
"""

import uuid
from datetime import datetime
from typing import Annotated

from sqlalchemy import DateTime, ForeignKey, MetaData, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention so autogenerated Alembic migrations produce
# stable, predictable constraint/index names instead of Postgres defaults.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


uuid_pk = Annotated[
    uuid.UUID,
    mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
]


class IdMixin:
    """Client-generatable UUID primary key — see SPRINT0.md §5.1 and §14.1.

    The id is never server-serial; it is generated wherever the record is
    first created (server or offline client) so offline-created records
    never need remapping on sync.
    """

    id: Mapped[uuid_pk]


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class CompanyScopedMixin:
    """Tenant-root scoping column, paired with Postgres RLS policies (§5.3).

    Split out from branch scoping because not every tenant-scoped table
    fits both: `Company` itself has no `company_id` (it IS the tenant),
    and `Branch` has a `company_id` but no `branch_id` (a branch isn't
    scoped to another branch) — see `app/modules/company/models.py`.
    """

    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False, index=True
    )


class BranchScopedMixin:
    """Optional branch scoping — nullable because some tenant-scoped
    records are company-wide rather than tied to one branch."""

    branch_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("branches.id"), nullable=True, index=True
    )


class SoftDeleteMixin:
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class ConcurrencyMixin:
    """Optimistic concurrency counter, incremented on every update."""

    version: Mapped[int] = mapped_column(default=1, nullable=False)


class SyncMixin:
    """Offline-sync metadata — see SPRINT0.md §14."""

    client_uuid: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    sync_status: Mapped[str] = mapped_column(String(20), default="synced", nullable=False)


class AuditMixin:
    """Actor tracking. Intentionally plain UUID columns, not FKs to
    `users.id` — every table in the system uses this mixin, including
    `users` itself (self-referential), so a hard FK would force strict
    table-creation ordering everywhere for marginal benefit. Referential
    integrity here is enforced at the service layer instead."""

    created_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    updated_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)


class TenantScopedModel(
    IdMixin,
    CompanyScopedMixin,
    BranchScopedMixin,
    TimestampMixin,
    SoftDeleteMixin,
    ConcurrencyMixin,
    SyncMixin,
    AuditMixin,
):
    """Convenience base combining every mixin a typical business table needs.

    Business modules should inherit `Base, TenantScopedModel` rather than
    composing mixins individually, unless a table has a genuine reason to
    omit one (e.g. a company-wide table with no `branch_id`) — in which
    case compose `CompanyScopedMixin` (and the others) directly instead.
    """

    __abstract__ = True
